[workspace]
members = [
  "crates/server",
  "crates/cli",
]
resolver = "2"

[workspace.package]
authors = ["Víctor García"]
edition = "2021"
license = "MIT"

# Config for 'cargo dist'
[workspace.metadata.dist]
# The preferred cargo-dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.4.1"
# CI backends to support
ci = ["github"]
# The installers to generate for each app
installers = ["shell", "powershell"]
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["x86_64-unknown-linux-gnu", "aarch64-apple-darwin", "x86_64-apple-darwin", "x86_64-pc-windows-msvc"]
# The archive format to use for non-windows builds (defaults .tar.xz)
unix-archive = ".tar.gz"
# Publish jobs to run in CI
pr-run-mode = "plan"
# Build only the required packages, and individually
precise-builds = true

[profile.release]
lto = true
opt-level = 3
strip="debuginfo"

# The profile that 'cargo dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
opt-level = "z"
codegen-units = 1
panic = "abort"
strip = true
