[workspace]
members = [
  "crates/server",
  "crates/cli",
]
resolver = "2"

[workspace.package]
authors = ["Víctor García"]
edition = "2021"
license = "MIT"

# Config for 'cargo dist'
[workspace.metadata.dist]
# The preferred cargo-dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.4.2"
# CI backends to support
ci = ["github"]
# The archive format to use for non-windows builds (defaults .tar.xz)
unix-archive = ".tar.gz"
# Publish jobs to run in CI
pr-run-mode = "plan"
# Build only the required packages, and individually
precise-builds = true

[profile.release]
codegen-units = 1
lto = "thin"
opt-level = "s"
strip = true

[profile.dist]
inherits = "release"
codegen-units = 1
lto = "thin"
opt-level = "s"
strip = true
