[package]
name = "query-runtime"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
base64-simd = "0.8.0"
bytes = "1.5.0"
fxhash = "0.2.1"
hex-simd = "0.8.0"
http-body-util = "0.1.1"
hyper = { version = "1.3.1", features = ["client", "http1", "http2"] }
hyper-rustls = { version = "0.27.1", default-features = false, features = ["http1", "http2", "ring", "webpki-tokio"] }
hyper-util = "0.1.3"
itoa = "1.0.10"
jsonwebtoken = "9.2"
once_cell = "1.19.0"
rbase64 = "2.0"
regex = "1.10"
ring = "0.17.8"
rquickjs = { version = "0.6.0", features = ["full-async", "parallel", "rust-alloc"] }
rusqlite = { version = "0.31", features = ["backup", "blob", "bundled", "functions", "limits", "serde_json", "trace", "uuid"] }
rustls = { version = "0.23.5", default-features = false, features = ["ring", "tls12"] }
ryu = "1.0.17"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
simd-json = { version = "0.13.10", default-features = false, features = ["big-int-as-float"] }
tokio = { version = "1", features = ["full"] }
tracing = { version = "0.1.40", features = ["log"] }
url = "2.5.0"
uuid = { version = "1.8.0", default-features = false, features = ["fast-rng", "v4"] }
uuid-simd = "0.8.0"
webpki-roots = "0.26.1"
