[package]
name = "query-runtime"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow = "1.0"
base64-simd = "0.8"
bytes = "1.8.0"
extism = "1.8.0"
extism-manifest = "1.9.0"
fxhash = "0.2"
hex-simd = "0.8"
http-body-util = "0.1"
hyper = { version = "1.5", features = ["client", "http1", "http2"] }
hyper-rustls = { version = "0.27", default-features = false, features = ["http1", "http2", "ring", "webpki-tokio"] }
hyper-util = "0.1"
itoa = "1.0"
jsonwebtoken = "9.3"
lettre = { version = "0.11.10", default-features = false, features = [
    "smtp-transport",
    "builder",
    "tokio1",
    "tokio1-native-tls",
] }
once_cell = "1.20"
rand = "0.8"
rbase64 = "2.0"
regex = "1.11"
ring = "0.17"
rquickjs = { version = "0.6.2", features = [
    "full-async",
    "parallel",
    "rust-alloc",
], default-features = false }
rusqlite = { version = "0.32", features = [
    "backup",
    "blob",
    "bundled",
    "functions",
    "limits",
    "serde_json",
    "trace",
    "uuid",
] }
rustls = { version = "0.23", default-features = false, features = [
    "ring",
    "tls12",
] }
ryu = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
simd-json = { version = "0.14", default-features = false, features = [
    "big-int-as-float",
] }
tokio = { version = "1", features = ["full"] }
tracing = { version = "0.1", features = ["log"] }
url = "2.5"
uuid = { version = "1.11", default-features = false, features = ["fast-rng", "v4"] }
uuid-simd = "0.8"
webpki-roots = "0.26"
