[package]
name = "query"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage = "https://github.com/gc-victor/query/tree/main/crates/cli"
repository = "https://github.com/gc-victor/query"

[features]
default = ["reqwest/default-tls"]
vendored-openssl = ["openssl/vendored"]
rustls = ["reqwest/rustls-tls"]

[dependencies]
anyhow = "1.0"
bincode = "1.3"
clap = { version = "4.4", features = ["derive"] }
inquire = "0.6"
lazy_static = "1.4"
liquid = "0.26"
mime_guess = "2.0.4"
rbase64 = "2.0"
regex = "1.10"
reqwest = { version = "0.11" }
rustyline = { version = "13" } 
serde =  { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
serde_json = "1.0"
tabled = "0.14"
toml = "0.8"
tokio = { version = "1.35", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"
walkdir = "2"

[dependencies.openssl]
version = "0.10"
features = ["vendored"]

[package.metadata.dist]
installers = ["shell", "powershell"]
targets = ["x86_64-unknown-linux-gnu", "aarch64-apple-darwin", "x86_64-apple-darwin", "x86_64-pc-windows-msvc"]
