[package]
name = "query"
version = "0.2.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage = "https://github.com/gc-victor/query/tree/main/crates/cli"
repository = "https://github.com/gc-victor/query"

[features]
default = ["reqwest/default-tls"]
vendored-openssl = ["openssl/vendored"]
rustls = ["reqwest/rustls-tls"]

[dependencies]
anyhow = "1.0"
bincode = "1.3"
clap = { version = "4.2", features = ["derive"] }
inquire = "0.6"
lazy_static = "1.4"
liquid = "0.26"
rbase64 = "2.0"
regex = "1.8"
reqwest = { version = "0.11" }
rustyline = { version = "12" } 
serde =  { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
serde_json = "1.0"
tabled = "0.14"
toml = "0.8"
tokio = { version = "1.28", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"
walkdir = "2"

[dependencies.openssl]
version = "0.10"
features = ["vendored"]

[build]
incremental = true