export const CONTINUE_CODE = 100;
export const SWITCHING_CODE = 101;
export const PROCESSING_CODE = 102;
export const OK_CODE = 200;
export const CREATED_CODE = 201;
export const ACCEPTED_CODE = 202;
export const NON_AUTHORITATIVE_CODE = 203;
export const NO_CONTENT_CODE = 204;
export const RESET_CONTENT_CODE = 205;
export const PARTIAL_CONTENT_CODE = 206;
export const MULTI_STATUS_CODE = 207;
export const ALREADY_REPORTED_CODE = 208;
export const IM_USED_CODE = 226;
export const MULTIPLE_CHOICES_CODE = 300;
export const MOVED_PERMANENTLY_CODE = 301;
export const FOUND_CODE = 302;
export const SEE_OTHER_CODE = 303;
export const NOT_MODIFIED_CODE = 304;
export const USE_PROXY_CODE = 305;
export const TEMPORARY_REDIRECT_CODE = 307;
export const PERMANENT_REDIRECT_CODE = 308;
export const BAD_REQUEST_CODE = 400;
export const UNAUTHORIZED_CODE = 401;
export const PAYMENT_REQUIRED_CODE = 402;
export const FORBIDDEN_CODE = 403;
export const NOT_FOUND_CODE = 404;
export const METHOD_NOT_ALLOWED_CODE = 405;
export const NOT_ACCEPTABLE_CODE = 406;
export const PROXY_AUTHENTICATION_REQUIRED_CODE = 407;
export const REQUEST_TIMEOUT_CODE = 408;
export const CONFLICT_CODE = 409;
export const GONE_CODE = 410;
export const LENGTH_REQUIRED_CODE = 411;
export const PRECONDITION_FAILED_CODE = 412;
export const REQUEST_ENTITY_TOO_LARGE_CODE = 413;
export const URI_TOO_LONG_CODE = 414;
export const UNSUPPORTED_MEDIA_TYPE_CODE = 415;
export const REQUESTED_RANGE_NOT_SATISFIABLE_CODE = 416;
export const EXPECTATION_FAILED_CODE = 417;
export const POLICY_NOT_FULFILLED_CODE = 420;
export const MISDIRECTED_REQUEST_CODE = 421;
export const UNPROCESSABLE_ENTITY_CODE = 422;
export const LOCKED_CODE = 423;
export const FAILED_DEPENDENCY_CODE = 424;
export const UPGRADE_REQUIRED_CODE = 426;
export const PRECONDITION_REQUIRED_CODE = 428;
export const TOO_MANY_REQUESTS_CODE = 429;
export const REQUEST_HEADER_FIELDS_TOO_CODE = 431;
export const UNAVAILABLE_FOR_LEGAL_REASONS_CODE = 451;
export const INTERNAL_SERVER_ERROR_CODE = 500;
export const NOT_IMPLEMENTED_CODE = 501;
export const BAD_GATEWAY_CODE = 502;
export const SERVICE_UNAVAILABLE_CODE = 503;
export const GATEWAY_TIMEOUT_CODE = 504;
export const HTTP_VERSION_NOT_SUPPORTED_CODE = 505;
export const VARIANT_ALSO_NEGOTIATES_CODE = 506;
export const INSUFFICIENT_STORAGE_CODE = 507;
export const LOOP_DETECTED_CODE = 508;
export const BANDWIDTH_LIMIT_EXCEEDED_CODE = 509;
export const NOT_EXTENDED_CODE = 510;
export const NETWORK_AUTHENTICATION_REQUIRED_CODE = 511;

export type StatusCode = {
    CONTINUE: number;
    SWITCHING: number;
    PROCESSING: number;
    OK: number;
    CREATED: number;
    ACCEPTED: number;
    NON_AUTHORITATIVE: number;
    NO_CONTENT: number;
    RESET_CONTENT: number;
    PARTIAL_CONTENT: number;
    MULTI_STATUS: number;
    ALREADY_REPORTED: number;
    IM_USED: number;
    MULTIPLE_CHOICES: number;
    MOVED_PERMANENTLY: number;
    FOUND: number;
    SEE_OTHER: number;
    NOT_MODIFIED: number;
    USE_PROXY: number;
    TEMPORARY_REDIRECT: number;
    PERMANENT_REDIRECT: number;
    BAD_REQUEST: number;
    UNAUTHORIZED: number;
    PAYMENT_REQUIRED: number;
    FORBIDDEN: number;
    NOT_FOUND: number;
    METHOD_NOT_ALLOWED: number;
    NOT_ACCEPTABLE: number;
    PROXY_AUTHENTICATION_REQUIRED: number;
    REQUEST_TIMEOUT: number;
    CONFLICT: number;
    GONE: number;
    LENGTH_REQUIRED: number;
    PRECONDITION_FAILED: number;
    REQUEST_ENTITY_TOO_LARGE: number;
    URI_TOO_LONG: number;
    UNSUPPORTED_MEDIA_TYPE: number;
    REQUESTED_RANGE_NOT_SATISFIABLE: number;
    EXPECTATION_FAILED: number;
    POLICY_NOT_FULFILLED: number;
    MISDIRECTED_REQUEST: number;
    UNPROCESSABLE_ENTITY: number;
    LOCKED: number;
    FAILED_DEPENDENCY: number;
    UPGRADE_REQUIRED: number;
    PRECONDITION_REQUIRED: number;
    TOO_MANY_REQUESTS: number;
    REQUEST_HEADER_FIELDS_TOO: number;
    UNAVAILABLE_FOR_LEGAL_REASONS: number;
    INTERNAL_SERVER_ERROR: number;
    NOT_IMPLEMENTED: number;
    BAD_GATEWAY: number;
    SERVICE_UNAVAILABLE: number;
    GATEWAY_TIMEOUT: number;
    HTTP_VERSION_NOT_SUPPORTED: number;
    VARIANT_ALSO_NEGOTIATES: number;
    INSUFFICIENT_STORAGE: number;
    LOOP_DETECTED: number;
    BANDWIDTH_LIMIT_EXCEEDED: number;
    NOT_EXTENDED: number;
    NETWORK_AUTHENTICATION_REQUIRED: number;
};

export const CONTINUE_MESSAGE = "Continue";
export const SWITCHING_MESSAGE = "Switching";
export const PROCESSING_MESSAGE = "Processing";
export const OK_MESSAGE = "Ok";
export const CREATED_MESSAGE = "Created";
export const ACCEPTED_MESSAGE = "Accepted";
export const NON_AUTHORITATIVE_MESSAGE = "Non Authoritative";
export const NO_CONTENT_MESSAGE = "No Content";
export const RESET_CONTENT_MESSAGE = "Reset Content";
export const PARTIAL_CONTENT_MESSAGE = "Partial Content";
export const MULTI_STATUS_MESSAGE = "Multi Status";
export const ALREADY_REPORTED_MESSAGE = "Already Reported";
export const IM_USED_MESSAGE = "Im Used";
export const MULTIPLE_CHOICES_MESSAGE = "Multiple Choices";
export const MOVED_PERMANENTLY_MESSAGE = "Moved Permanently";
export const FOUND_MESSAGE = "Found";
export const SEE_OTHER_MESSAGE = "See Other";
export const NOT_MODIFIED_MESSAGE = "Not Modified";
export const USE_PROXY_MESSAGE = "Use Proxy";
export const TEMPORARY_REDIRECT_MESSAGE = "Temporary Redirect";
export const PERMANENT_REDIRECT_MESSAGE = "Permanent Redirect";
export const BAD_REQUEST_MESSAGE = "Bad Request";
export const UNAUTHORIZED_MESSAGE = "Unauthorized";
export const PAYMENT_REQUIRED_MESSAGE = "Payment Required";
export const FORBIDDEN_MESSAGE = "Forbidden";
export const NOT_FOUND_MESSAGE = "Not Found";
export const METHOD_NOT_ALLOWED_MESSAGE = "Method Not Allowed";
export const NOT_ACCEPTABLE_MESSAGE = "Not Acceptable";
export const PROXY_AUTHENTICATION_REQUIRED_MESSAGE = "Proxy Authentication Required";
export const REQUEST_TIMEOUT_MESSAGE = "Request Timeout";
export const CONFLICT_MESSAGE = "Conflict";
export const GONE_MESSAGE = "Gone";
export const LENGTH_REQUIRED_MESSAGE = "Length Required";
export const PRECONDITION_FAILED_MESSAGE = "Precondition Failed";
export const REQUEST_ENTITY_TOO_LARGE_MESSAGE = "Request Entity Too Large";
export const URI_TOO_LONG_MESSAGE = "Uri Too Long";
export const UNSUPPORTED_MEDIA_TYPE_MESSAGE = "Unsupported Media Type";
export const REQUESTED_RANGE_NOT_SATISFIABLE_MESSAGE = "Requested Range Not Satisfiable";
export const EXPECTATION_FAILED_MESSAGE = "Expectation Failed";
export const POLICY_NOT_FULFILLED_MESSAGE = "Policy Not Fulfilled";
export const MISDIRECTED_REQUEST_MESSAGE = "Misdirected Request";
export const UNPROCESSABLE_ENTITY_MESSAGE = "Unprocessable Entity";
export const LOCKED_MESSAGE = "Locked";
export const FAILED_DEPENDENCY_MESSAGE = "Failed Dependency";
export const UPGRADE_REQUIRED_MESSAGE = "Upgrade Required";
export const PRECONDITION_REQUIRED_MESSAGE = "Precondition Required";
export const TOO_MANY_REQUESTS_MESSAGE = "Too Many Requests";
export const REQUEST_HEADER_FIELDS_TOO_MESSAGE = "Request Header Fields Too";
export const UNAVAILABLE_FOR_LEGAL_REASONS_MESSAGE = "Unavailable For Legal Reasons";
export const INTERNAL_SERVER_ERROR_MESSAGE = "Internal Server Error";
export const NOT_IMPLEMENTED_MESSAGE = "Not Implemented";
export const BAD_GATEWAY_MESSAGE = "Bad Gateway";
export const SERVICE_UNAVAILABLE_MESSAGE = "Service Unavailable";
export const GATEWAY_TIMEOUT_MESSAGE = "Gateway Timeout";
export const HTTP_VERSION_NOT_SUPPORTED_MESSAGE = "Http Version Not Supported";
export const VARIANT_ALSO_NEGOTIATES_MESSAGE = "Variant Also Negotiates";
export const INSUFFICIENT_STORAGE_MESSAGE = "Insufficient Storage";
export const LOOP_DETECTED_MESSAGE = "Loop Detected";
export const BANDWIDTH_LIMIT_EXCEEDED_MESSAGE = "Bandwidth Limit Exceeded";
export const NOT_EXTENDED_MESSAGE = "Not Extended";
export const NETWORK_AUTHENTICATION_REQUIRED_MESSAGE = "Network Authentication Required";

export type StatusMessage = {
    CONTINUE: string;
    SWITCHING: string;
    PROCESSING: string;
    OK: string;
    CREATED: string;
    ACCEPTED: string;
    NON_AUTHORITATIVE: string;
    NO_CONTENT: string;
    RESET_CONTENT: string;
    PARTIAL_CONTENT: string;
    MULTI_STATUS: string;
    ALREADY_REPORTED: string;
    IM_USED: string;
    MULTIPLE_CHOICES: string;
    MOVED_PERMANENTLY: string;
    FOUND: string;
    SEE_OTHER: string;
    NOT_MODIFIED: string;
    USE_PROXY: string;
    TEMPORARY_REDIRECT: string;
    PERMANENT_REDIRECT: string;
    BAD_REQUEST: string;
    UNAUTHORIZED: string;
    PAYMENT_REQUIRED: string;
    FORBIDDEN: string;
    NOT_FOUND: string;
    METHOD_NOT_ALLOWED: string;
    NOT_ACCEPTABLE: string;
    PROXY_AUTHENTICATION_REQUIRED: string;
    REQUEST_TIMEOUT: string;
    CONFLICT: string;
    GONE: string;
    LENGTH_REQUIRED: string;
    PRECONDITION_FAILED: string;
    REQUEST_ENTITY_TOO_LARGE: string;
    URI_TOO_LONG: string;
    UNSUPPORTED_MEDIA_TYPE: string;
    REQUESTED_RANGE_NOT_SATISFIABLE: string;
    EXPECTATION_FAILED: string;
    POLICY_NOT_FULFILLED: string;
    MISDIRECTED_REQUEST: string;
    UNPROCESSABLE_ENTITY: string;
    LOCKED: string;
    FAILED_DEPENDENCY: string;
    UPGRADE_REQUIRED: string;
    PRECONDITION_REQUIRED: string;
    TOO_MANY_REQUESTS: string;
    REQUEST_HEADER_FIELDS_TOO: string;
    UNAVAILABLE_FOR_LEGAL_REASONS: string;
    INTERNAL_SERVER_ERROR: string;
    NOT_IMPLEMENTED: string;
    BAD_GATEWAY: string;
    SERVICE_UNAVAILABLE: string;
    GATEWAY_TIMEOUT: string;
    HTTP_VERSION_NOT_SUPPORTED: string;
    VARIANT_ALSO_NEGOTIATES: string;
    INSUFFICIENT_STORAGE: string;
    LOOP_DETECTED: string;
    BANDWIDTH_LIMIT_EXCEEDED: string;
    NOT_EXTENDED: string;
    NETWORK_AUTHENTICATION_REQUIRED: string;
};
