[server]
url = "http://localhost:3000"

[structure]
functions_folder = "src"

[esbuild]
"external:query:database" = ""
"jsx" = "preserve"

[task]
clean = ".query/tasks/clean.sh"
deploy = ".query/tasks/deploy.sh"
bundle = ".query/tasks/bundle.sh"
tailwind = "node_modules/.bin/tailwindcss -i ./src/pages/styles.css -o ./dist/styles.css"

[task.create]
deploy = ".query/tasks/deploy.sh"

[task.dev]
bundle = ".query/tasks/bundle.sh & node_modules/.bin/tailwindcss -i ./src/pages/styles.css -o ./dist/styles.css"
