[package]
name = "jsx_parser"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
regex = "1.11.1"

[dev-dependencies]
criterion = "0.6"

[[bench]]
name = "jsx_parser"
harness = false
test = false
