[package]
name = "query-server"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "Server for SQLite databases."
homepage = "https://github.com/gc-victor/query/tree/main/crates/server"
repository = "https://github.com/gc-victor/query"

[dependencies]
anyhow = "1.0"
argon2 = "0.5"
chacha20poly1305 = { version = "0.10" }
dotenv = "0.15"
hyper = { version = "1.1", features = ["full"] }
hyper-util = { version = "0.1", features = ["full"] }
http-body-util = "0.1"
jsonwebtoken = "9.2"
rbase64 = "2.0"
regex = "1.10"
rusqlite = { version = "0.30", features = [
    "bundled",
    "backup",
    "limits",
    "functions",
    "uuid",
    "blob",
    "trace",
    "serde_json",
] }
rustyscript = { version = "0.3.0", features = ["all"] }
serde = { version = "1.0", features = ["derive"] }
serde_bytes = "0.11"
serde_json = "1.0"
sha2 = "0.10"
tokio = { version = "1.36", features = ["full"] }
tracing = { version = "0.1", features = ["log"] }
tracing-bunyan-formatter = "0.3"
tracing-log = "0.2"
tracing-subscriber = { version = "0.3", features = [
    "registry",
    "env-filter",
    "fmt",
    "json",
    "std",
] }
url = "2.5"
uuid = { version = "1.7", features = ["v4"] }
