name: Web Docs

on:
  push:
    branches:
      - main
    tags:
      - "**[0-9]+.[0-9]+.[0-9]+*"
    paths:
      - examples/docs/**
      - .github/workflows/docs.yml

env:
  CARGO_TERM_COLOR: always

jobs:
  web-docs:
    name: Web Docs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # selecting a toolchain either by action or manual `rustup` calls should happen
      # before the plugin, as the cache uses the current rustc version as its cache key
      - run: rustup toolchain install stable --profile minimal

      - name: Rust Cache Action
        uses: Swatinem/rust-cache@v2

      - name: Cache
        id: query-cache
        uses: actions/cache@v4
        with:
          path: examples/docs/.query/.cache
          key: query-cache-${{ github.run_id }}
          restore-keys: query-cache

      - name: Use pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install dependencies
        run: |
          cd examples/docs
          pnpm install

      - name: Create docs
        env:
          RUST_BACKTRACE: full
          RUST_LOG: info
        run: |
          cargo run --package query-docs -- --input examples/docs/docs --output examples/docs/dist/docs

      - name: Debug dist directory
        run: |
          find examples/docs/dist/docs -type f | sort

      - name: Set token
        env:
          QUERY_WEB_PRIVATE_TOKEN: ${{ secrets.QUERY_WEB_PRIVATE_TOKEN }}
        run: |
          cd examples/docs
          echo "[default] $QUERY_WEB_PRIVATE_TOKEN" > .query/.token

      - name: Set remote URL
        run: |
          cd examples/docs
          sed -i "s|http://localhost:3000|https://qery.io|" .query/Query.toml

      - name: Deploy to qery.io
        run: |
          cd examples/docs
          ./node_modules/.bin/tailwindcss -i ./docs/styles.css -o ./dist/docs/styles.css
          ./node_modules/.bin/query asset dist
          ./node_modules/.bin/query function src/pages/docs/get.index.tsx
          ./node_modules/.bin/query function src/pages/docs/\[slug\]/get.index.tsx
          ./node_modules/.bin/query function src/pages/docs/\[slug\]/\[slug\]/get.index.tsx

      - name: Cache content
        run: |
          cd examples/docs
          cat .query/.cache
