name: Tests

on:
  push:
    branches:
      - main
    tags:
      - "**[0-9]+.[0-9]+.[0-9]+*"
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  unit-test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # selecting a toolchain either by action or manual `rustup` calls should happen
      # before the plugin, as the cache uses the current rustc version as its cache key
      - run: rustup toolchain install stable --profile minimal
      - name: Rust Cache Action
        uses: Swatinem/rust-cache@v2
      - name: Run unit tests
        env:
          RUST_BACKTRACE: full
          RUST_LOG: info
          QUERY_SERVER_PORT: 3000
          QUERY_SERVER_DBS_PATH: /tmp/dbs
          QUERY_SERVER_TOKEN_SECRET: secret
          QUERY_SERVER_ADMIN_EMAIL: admin
          QUERY_SERVER_ADMIN_PASSWORD: admin
        run: |
          rustup update stable && rustup default stable
          cargo test -- --test-threads=1

  integration-test:
    name: Integration tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # selecting a toolchain either by action or manual `rustup` calls should happen
      # before the plugin, as the cache uses the current rustc version as its cache key
      - run: rustup toolchain install stable --profile minimal
      - name: Rust Cache Action
        uses: Swatinem/rust-cache@v2
      - name: Install Hurl
        run: |
          curl -LO https://github.com/Orange-OpenSource/hurl/releases/download/4.1.0/hurl_4.1.0_amd64.deb
          sudo dpkg -i hurl_4.1.0_amd64.deb
          hurl --version
      - name: Build query-server
        env:
          RUST_BACKTRACE: full
          RUST_LOG: info
        run: |
          rustup update stable && rustup default stable
          cargo build --package=query-server --release
      - name: Run query-server
        env:
          RUST_BACKTRACE: full
          RUST_LOG: info
          QUERY_SERVER_PORT: 3000
          QUERY_SERVER_DBS_PATH: /tmp/dbs
          QUERY_SERVER_TOKEN_SECRET: secret
          QUERY_SERVER_ADMIN_EMAIL: admin
          QUERY_SERVER_ADMIN_PASSWORD: admin
        run: |
          mkdir -p $QUERY_SERVER_DBS_PATH
          chmod +x $QUERY_SERVER_DBS_PATH
          chmod g+s $QUERY_SERVER_DBS_PATH
          target/release/query-server &
      - name: Run integration tests
        run: |
          make hurl-test-all
